language: java
install: true
before_install:
 - chmod +x gradlew

os: linux
dist: trusty
jdk: oraclejdk8

script:
  - ./gradlew clean build
  - ./gradlew clean check
  - ./gradlew clean codeCoverageReport
  
after_success:
  - bash <(curl -s https://codecov.io/bash)