/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ds.codility;

/**
 * @author Sarvesh Dubey
 *
 */
public class Leader {

    /**
     * Given an Integer array, finds the leader. A leader of an array is the element
     * which appears in the array for more than half the length of its size. <br>
     * Example 1: If array is [2,,3,4,4,4], then leader is 4. <br>
     * Example 2: If array is [1,2,2,3], then there is no leader, or the leader is
     * -1 <br>
     * 
     * @param A
     *            Integer array
     * @return the leader element if present else -1
     */
    public static int findLeader(int[] A) {
        if (A.length == 0)
            return -1;
        if (A.length == 1)
            return A[0];
        int candidate = 0;
        int count = 0;
        for (int i : A) {
            if (count == 0) {
                candidate = i;
                count++;
            } else if (candidate == i) {
                count++;
            } else {
                count--;
            }
        }
        return count > A.length / 2 ? candidate : -1;
    }

    public static int findLeader1(int[] A) {
        int[] counts = new int[100000];
        for (int i : A) {
            counts[i] = counts[i] + 1;
        }
        for (int j = 0; j < counts.length; j++) {
            if (counts[j] > A.length / 2)
                return j;
        }
        return -1;

    }
}
